DROP IF EXISTS TB_CLIENTE
CREATE TABLE TB_CLIENTE
(
	CODCLI 		INT IDENTITY(1,1) NOT NULL,
	NOME 		VARCHAR(50) NULL,
	FANTASIA 	VARCHAR(20) NULL,
	ENDERECO 	VARCHAR(60) NULL,
	BAIRRO 		VARCHAR(20) NULL,
	CIDADE 		VARCHAR(20) NULL,
	ESTADO 		VARCHAR(2) NULL,
	CEP 		VARCHAR(8) NULL,
	END_COB 	VARCHAR(60) NULL,
	BAI_COB 	VARCHAR(20) NULL,
	CID_COB 	VARCHAR(20) NULL,
	EST_COB 	VARCHAR(2) NULL,
	CEP_COB 	VARCHAR(8) NULL,
	CNPJ 		VARCHAR(18) NULL,
	INSCRICAO 	VARCHAR(19) NULL,
	FONE1 		VARCHAR(15) NULL,
	FAX 		VARCHAR(15) NULL,
	E_MAIL 		VARCHAR(35) NULL,
	DATA_CAD 	DATETIME NULL,
	ICMS 		FLOAT NULL,
	REVENDA_CONSUMIDOR CHAR(1) NULL,
 CONSTRAINT PK__CLIENTE PRIMARY KEY CLUSTERED (CODCLI ASC) ON [PRIMARY]
 );

DROP IF EXISTS TB_VENDEDOR
CREATE TABLE TB_VENDEDOR
(
	CODVEN 		SMALLINT IDENTITY(1,1) NOT NULL,
	NOME 		VARCHAR(50) NULL,
	FANTASIA 	VARCHAR(20) NULL,
	ENDERECO 	VARCHAR(60) NULL,
	BAIRRO 		VARCHAR(20) NULL,
	CIDADE 		VARCHAR(20) NULL,
	ESTADO 		VARCHAR(2) NULL,
	CEP 		VARCHAR(8) NULL,
	CPF 		VARCHAR(18) NULL,
	RG 		VARCHAR(15) NULL,
	FONE 		VARCHAR(15) NULL,
	FAX 		VARCHAR(15) NULL,
	E_MAIL 		VARCHAR(35) NULL,
	DATA_CAD 	DATETIME NULL,
	DATA_NASC 	DATETIME NULL,
	PORC_COMISSAO 	decimal(5, 2) NULL,
 CONSTRAINT PK__VENDEDOR__145C0A3F PRIMARY KEY CLUSTERED (CODVEN ASC) ON [PRIMARY]
 );

DROP IF EXISTS TB_PRODUTO
CREATE TABLE TB_PRODUTO
(
	ID_PRODUTO 	INT IDENTITY(1,1) NOT NULL,
	COD_PRODUTO 	VARCHAR(13) NOT NULL,
	DESCRICAO 	VARCHAR(40) NULL,
	COD_UNIDADE 	SMALLINT NULL,
	COD_TIPO 	SMALLINT NULL,
	PRECO_CUSTO 	NUMERIC(18, 4) NULL,
	PRECO_VENDA 	NUMERIC(18, 4) NULL,
	QTD_ESTIMADA 	INT NULL,
	QTD_REAL 	INT NULL,
	QTD_MINIMA 	INT NULL,
	CLAS_FISC 	VARCHAR(10) NULL,
	IPI 		INT NULL,
	PESO_LIQ 	NUMERIC(18, 2) NULL,
 CONSTRAINT PK__PRODUTS PRIMARY KEY CLUSTERED (ID_PRODUTO ASC) ON [PRIMARY]
 );

DROP IF EXISTS TB_PEDIDO
CREATE TABLE TB_PEDIDO
(
	NUM_PEDIDO 	INT IDENTITY(1,1) NOT NULL,
	CODCLI 		INT NULL,
	CODVEN 		SMALLINT NULL,
	DATA_EMISSAO 	DATETIME NULL,
	VLR_TOTAL 	NUMERIC(18, 2) NULL,
	SITUACAO 	VARCHAR(1) NULL,
	OBSERVACOES 	TEXT NULL,
 CONSTRAINT PK__PEDIDS PRIMARY KEY CLUSTERED (NUM_PEDIDO ASC) ON [PRIMARY]
 );

DROP IF EXISTS TB_ITENSPEDIDO
CREATE TABLE TB_ITENSPEDIDO
(
	NUM_PEDIDO 	INT NOT NULL,
	NUM_ITEM 	SMALLINT NOT NULL,
	ID_PRODUTO 	INT NULL,
	COD_PRODUTO 	VARCHAR(13) NULL,
	CODCOR 		SMALLINT NULL,
	QUANTIDADE 	INT NULL,
	PR_UNITARIO 	NUMERIC(18, 4) NULL,
	DATA_ENTREGA 	DATETIME NULL,
	SITUACAO 	VARCHAR(1) NULL,
	DESCONTO 	FLOAT NULL,
 CONSTRAINT PK__ITENSPEDIDO PRIMARY KEY CLUSTERED (NUM_PEDIDO ASC, NUM_ITEM ASC) ON [PRIMARY]
 );
